pipeline:
  markdownlint:
    image: g3dev/lintmd
    pull: true
  setup-builddata:
    image: g3dev/nodedev
    commands:
    - cat build_data.yml.template | sed "s/__BRANCH__/${DRONE_COMMIT_BRANCH}/g" | sed "s/__SHA__/${DRONE_COMMIT_SHA}/g" > build_data.yml
  build-dockerfile:
    image: g3dev/jinja2cli
    pull: true
    template: Dockerfile.j2
    data: build_data.yml
    outfile: Dockerfile
  build-tags-branch:
    image: g3dev/jinja2cli
    template: tags-branch.j2
    data: build_data.yml
    outfile: .tags
    when:
      exclude: [ master ]
  build-tags-master:
    image: g3dev/jinja2cli
    template: tags-master.j2
    data: build_data.yml
    outfile: .tags
    when:
      branch: master
  publish:
    image: plugins/docker
    repo: g3dev/lintmd
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push, tag ]
  notify-email:
    image: drillster/drone-email
    from: no-reply@griffingroupglobal.com
    secrets: [ email_username, email_password, email_recipients, email_host ]
    subject: >
      drone.g3dev.io - [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ commit.branch }} - {{ commit.link }})
    when:
      branch: master
      status: [ success, failure ]
      event: [ push, tag, deployment ]
  notify-slack:
    image: plugins/slack-blame
    secrets: [ slack_token ]
    channel: gravity_build
    mapping:
      MattAtG3: matt.jenks@griffingroupglobal.com
    success_template: |
      The build ${DRONE_REPO_NAME} was fixed by commit author @${DRONE_COMMIT_AUTHOR}! Thanks @{{slack.name}}
    success_image_attachments:
      - "http://i.imgur.com/TP4PIxc.jpg"
    failure_template: |
      The build ${DRONE_REPO_NAME} was broken by commit author @${DRONE_COMMIT_AUTHOR}! Blame @{{slack.name}}
    failure_image_attachments:
      - "https://raw.githubusercontent.com/drone-plugins/drone-slack-blame/master/memes/kittens_fail.jpg"
    when:
      branch: master
      status: [ success, failure ]
      event: [ push, tag, deployment ]
