FROM g3dev/nodedev:{{ base_version }}
LABEL maintainer="{{ maintainer }}"

WORKDIR /home/node

COPY package.json .
COPY markdownlint.json .
COPY runlint.sh .

RUN npm install

ENV NODE_ENV {{ node_env }}

CMD ["/home/node/runlint.sh"]
